CREATE DATABASE customer_behavior;


select * from customer limit 10;


-- Q1. What is the total revenue generated by male vs. female customers

SELECT gender, SUM(`purchase amount (usd)`) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT `customer id`, `purchase amount (usd)`
FROM customer
WHERE `discount applied` = 'Yes'
  AND `purchase amount (usd)` >= (
      SELECT AVG(`purchase amount (usd)`)
      FROM customer
  );


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `item purchased`,
       ROUND(AVG(`review rating`), 2) AS `Average Product Rating`
FROM customer
GROUP BY `item purchased`
ORDER BY AVG(`review rating`) DESC
LIMIT 5;


#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT `shipping type`,
       ROUND(AVG(`purchase amount (usd)`), 2) AS average_purchase
FROM customer
WHERE `shipping type` IN ('Standard', 'Express')
GROUP BY `shipping type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT `subscription status`,
       ROUND(AVG(`purchase amount (usd)`), 2) AS average_spend,
       ROUND(SUM(`purchase amount (usd)`), 2) AS total_revenue
FROM customer
GROUP BY `subscription status`;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT `item purchased`,
       ROUND(
           SUM(CASE WHEN `discount applied` = 'Yes' THEN 1 ELSE 0 END)
           * 100.0 / COUNT(*), 2
       ) AS discount_percentage
FROM customer
GROUP BY `item purchased`
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
SELECT `customer id`,
       `previous purchases`,
       CASE
           WHEN `previous purchases` = 0 THEN 'New'
           WHEN `previous purchases` BETWEEN 1 AND 5 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customer;


-- Q8. What are the top 3 most purchased products within each category? 
WITH product_counts AS (
    SELECT
        category,
        `item purchased`,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer
    GROUP BY category, `item purchased`
)
SELECT category,
       `item purchased`,
       purchase_count
FROM product_counts
WHERE product_rank <= 3
ORDER BY category, purchase_count DESC;


 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    CASE
        WHEN `previous purchases` > 5 THEN 'Repeat Buyer'
        ELSE 'Not Repeat Buyer'
    END AS buyer_type,
    `subscription status`,
    COUNT(*) AS customer_count
FROM customer
GROUP BY buyer_type, `subscription status`
ORDER BY buyer_type, `subscription status`;


-- Q10. What is the revenue contribution of each age group? 

SELECT age_group,
       ROUND(SUM(`purchase amount (usd)`), 2) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;
